# Generated by Django 3.1.3 on 2020-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripeCustomerId',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripeSubscriptionId',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
