# Generated by Django 3.1.3 on 2020-11-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('preview_img', models.ImageField(default='default.png', upload_to='productprev/')),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='productImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_imgs', models.ImageField(default='default.png', upload_to='productimg/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
    ]
