# Generated by Django 3.1.3 on 2020-11-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='event_imgs',
            new_name='prod_imgs',
        ),
    ]
