# Generated by Django 3.1.3 on 2020-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20201118_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='pdf',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='prod_imgs',
            field=models.ImageField(default='default.png', upload_to='media/productimg/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preview_img',
            field=models.ImageField(default='default.png', upload_to='media/productprev/'),
        ),
    ]
