# Generated by Django 3.1.3 on 2020-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20201119_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pdf',
            field=models.FileField(default='default.png', upload_to='media/pdfs/'),
        ),
    ]
