# Generated by Django 3.1.3 on 2020-12-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201201_0546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='behind_the_scenese',
            new_name='behind_the_scene',
        ),
    ]
