# Generated by Django 3.1.3 on 2020-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201201_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behind_the_scene',
            name='display_img',
            field=models.ImageField(default='default.png', upload_to='media/gallery/scenes/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='display_img',
            field=models.ImageField(default='default.png', upload_to='media/gallery/movies/'),
        ),
    ]
